# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7c25ac92da1b07d59a9541e5ddda680a3a7efd3c4435256ffa76dc88258e7a6b0fbed5c8eecc8ff2b9280d262c853f695be6603dbac3205c478ef312857db00c

test:
  secret_key_base: a347c9004dd63ecc3f91b70d302d9b631cd2360fe4184191c57dbd743110b49e300fcfacffc3686b0d5d5402af065b90c2e70fe914bc745bb4632fe3926ccc6a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
